--insert into student (rollno, name, marks) values(10, 'Kevin', 79);
--insert into student (rollno, name, marks) values(20, 'Starboy', 68);
--insert into student (rollno, name, marks) values(30, 'Kartel', 84);